# Mapeamento de abreviações para nomes de unidade exatos do banco de dados.
# Chave   = abreviação (como o usuário pode digitar)
# Valor   = nome da unidade exato gravado na coluna `Fantasia` do banco
#
# Para adicionar ou ajustar um de/para, edite apenas este arquivo.

ABREVIACAO_TO_FANTASIA: dict[str, str] = {
    "BPBARRA":          "UNIDADE A BARRA",
    "BPBSB":            "UNIDADE A BRASILIA",
    "BPCWB":            "UNIDADE A CURITIBA",
    "BPI":              "UNIDADE A ITAIM",
    "BPIPA":            "UNIDADE A IPANEMA",
    "BPL":              "UNIDADE A RJ",
    "BPM":              "UNIDADE A MORUMBI",
    "BPP":              "UNIDADE A PAULISTA",
    "COZINHA CENTRAL":  "COZINHA CENTRAL",
    "DM IPA":           "UNIDADE B IPA",
    "DM ITAIM":         "UNIDADE B ITAIM",
    "DM MORUMBI":       "UNIDADE B MORUMBI",
    "ETEP":             "UNIDADE C PAULISTA",
    "FORNO":            "UNIDADE D",
    "UNIDADE E":        "UNIDADE E MATRIZ",
    "NT BARRA":         "UNIDADE F RIO DESIGN",
    "NT BH":            "UNIDADE F BH",
    "NT CAMPINAS":      "UNIDADE F DOM PEDRO",
    "NT CURITIBA":      "UNIDADE F BARIGUI",
    "NT ELDORADO":      "UNIDADE F ELDORADO",
    "NT FORTALEZA":     "UNIDADE F FORTALEZA",
    "NT MORUMBI":       "UNIDADE F MORUMBI",
    "NT RECIFE":        "UNIDADE F RECIFE",
    "NT UBERLANDIA":    "UNIDADE F UBERLANDIA",
    "LOJA BH":          "UNIDADE G BELO HORIZONTE",
    "LOJA BSB":         "UNIDADE G BRASILIA",
    "LOJA CC":          "UNIDADE G CC",
    "LOJA GOIANIA":     "UNIDADE G GOIANIA",
    "LOJA IPANEMA":     "UNIDADE G IPA",
    "LOJA ITAIM":       "UNIDADE G ITAIM",
    "UNIDADE H":          "UNIDADE H CANTINA",
    "PRI BARRA":        "UNIDADE I BARRA",
    "PRI LEBLON":       "UNIDADE I LEBLON",
    "RNH BARRA":        "UNIDADE J BARRA",
    "RNH CLODOMIRO":    "UNIDADE J ITAIM",
    "RNH LEBLON":       "UNIDADE J LEBLON",
    "RNH PAULISTA":     "UNIDADE J PAULISTA",
    "RNH PEDROSO":      "UNIDADE J SP",
    "LOJA K BARRA":      "UNIDADE K BARRA",
    "LOJA K LEBLON":     "UNIDADE K LEBLON",
    "LOJA K RIO SUL":    "UNIDADE K RIO SUL",
    "TBBH":             "UNIDADE L BH",
    "TBCAMP":           "UNIDADE L CAMPINAS",
    "TBCG":             "UNIDADE L CAMPO GRANDE",
    "TBF":              "UNIDADE L FORTALEZA",
    "TBG":              "UNIDADE L GOIANIA",
    "TBI":              "UNIDADE L ITAIM",
    "TBJ":              "UNIDADE L JARDINS",
    "TBPAMP":           "UNIDADE L PAMPULHA",
    "TBREC":            "UNIDADE L RECIFE",
    "TBRP":             "UNIDADE L RIBEIRAO PRETO",
    "TBSSA":            "UNIDADE L SALVADOR",
    "TBT":              "UNIDADE L TATUAPE",
    "TBU":              "UNIDADE L UBERLANDIA",
    "TBVO":             "UNIDADE L VILA OLIMPIA",
    "TBZN":             "UNIDADE L ZONA NORTE",
    "TTZPOMP":          "UNIDADE M POMPEIA",
}
